# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "sbeliakou/centos-6.7-x86_64"
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.hostname = "ansible"
  config.vm.network :private_network, ip: "192.168.56.23"
  config.vm.provider "virtualbox" do |vb|
    vb = config.vm.hostname
  end

  config.vm.provision "shell", inline: <<-SHELL
  mkdir -p /home/vagrant/.ssh/
  cp id_rsa.pub /home/vagrant/.ssh/
  cat /home/vagrant/.ssh/id_rsa.pub | 'cat >> /home/vagrant/.ssh/authorized_keys'
  chmod 700 /home/vagrant/.ssh
  chmod 640 /home/vagrant/.ssh/authorized_keys

  SHELL
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = 'ansible/provision.yml'
    ansible.verbose = 'vv'
  end
end
