# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos-7.3-x86_64-minimal.box"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.hostname = "pet"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb = config.vm.hostname
  end
end
